# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "schedules", :force => true do |t|
    t.column "today",   :date
    t.column "user_id", :integer
  end

  create_table "tasks", :force => true do |t|
    t.column "name",       :string
    t.column "complete",   :datetime
    t.column "due",        :date
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "user_id",    :integer
  end

  create_table "todos", :force => true do |t|
    t.column "schedule_id", :integer
    t.column "task_id",     :integer
    t.column "position",    :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
  end

end
